vax/liveimage: exclude man page sets etc. to fix live-image build
Tested on open-simh:
---
NetBSD 11.99.4 (GENERIC) #0: Fri Jan 16 03:16:14 JST 2026

Welcome to NetBSD!

This is a development snapshot of NetBSD for testing -- user beware!

Bug reports: https://www.NetBSD.org/support/send-pr.html
Donations to the NetBSD Foundation: https://www.NetBSD.org/donations/
We recommend that you create a non-root account and use su(1) for root access.
No entry for terminal type "unknown";
using dumb terminal settings.
# df
Filesystem      1K-blocks         Used        Avail %Cap Mounted on
/dev/ra0a          965166       904188        12720  99% /
ptyfs                   1            1            0 100% /dev/pts
tmpfs               65508            4        65504   1% /var/shm
#
---

Note 1.5GB image causes fsck_ffs(8) error on open-simh:
---
Starting root file system check:
/dev/rra0a: BAD SUPER BLOCK: VALUES IN SUPER BLOCK DISAGREE WITH THOSE IN FIRST ALTERNATE

/dev/rra0a: UNEXPECTED INCONSISTENCY; RUN fsck_ffs MANUALLY.
Automatic file system check failed; help!
ERROR: ABORTING BOOT (sending SIGTERM to parent)!
---