hppa: Add some rumplish 64-bit atomics to librump.so.
Should really fix rump build on hppa since a new use of atomic_inc_64
under __HAVE_ATOMIC64_OPS sprouted a few days ago:

/home/builds/ab/HEAD/hppa/20260917233410Z-tools/lib/gcc/hppa--netbsd/14.3.0/../../../../hppa--netbsd/bin/ld: /home/builds/ab/HEAD/hppa/20260917233410Z-dest/usr/lib/librumpnet_local.so: undefined reference to `rumpns_atomic_inc_64_nv'

Followup for:

PR kern/60729: incosistent st_ino from the first stat(2) on a socket